# This is a basic workflow to help you get started with Actions

name: Test-Build-

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Install Node
        uses: action/setup-node@v1
        with:
          node-version: "12.x"
          
      - name: Install newman   
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      - name: Make directory for results
        run: mkdir -p testResults
        
      - name: Run Postman collection
        run: |
          newman run store.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html
        
      - name: Output the run details
        uses: actions/upload-artifact@2
        with:
          name: RunReports
          path: testResults
          
      


